name: percy
channels:
  - defaults

dependencies:
  - black
  - isort
  - make
  - mypy
  - python >=3.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - pylint
  - pip
  - click>=8.1.7
  - conda
  - jinja2
  - pyyaml
  - types-pyyaml
  - requests
  - types-requests
  - ruamel.yaml
  - ruamel.yaml.jinja2
  - conda-build
  - jsonschema
  - types-jsonschema
  - pre-commit
  - conda-recipe-manager
