name: Set up environment
description: Set up an percy environment

inputs:
  python-version:
    description: "Version of python to use in the conda environment."
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f  # v3.2.0
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: percy
        environment-file: environment.yaml
    - name: Create Environment
      shell: bash
      run: |
        source $CONDA/bin/activate
        conda activate percy
        pip install .
