name: Set up environment
description: Set up an percy environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Cache conda env
      id: cache-conda
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      env:
        cache-name: conda-env-cache
      with:
        cache: 'pip'
        path: '/usr/share/miniconda/envs'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Environment
      shell: bash
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      # NOTE: We use `sed` to force a Python version in the `environment.yaml` file
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        sed -i 's/- python >=3.*$/- python ${{ inputs.python-version }}.*/' environment.yaml
        conda env create -f environment.yaml --name percy
        conda run --name percy pip install .
