on:
  push:
    branches:
      - main
  pull_request:

name: Test

jobs:
  # NOTE: Tests run via `pre-commit`
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
        # Executes `pre-commit` with the `make` directive to ensure all dependencies are found
        - run: |
            source $CONDA/bin/activate
            conda activate percy
            make pre-commit
  test:
      runs-on: ubuntu-latest
      name: Test on ${{ matrix.python-version }}
      strategy:
        matrix:
          python-version: ["3.11"] # TODO: Bump this to 3.12 when supported and drop 3.11 (covered in pre-commit)
      steps:
        - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        - uses: ./.github/actions/setup-env
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            source $CONDA/bin/activate
            conda activate percy
            make test
